/* 
 * webCRM REST API
 *
 * Version: 1.0.0.0.<br>Note that you can access live data through this web site, so be careful when updating or deleting things.
 *
 * OpenAPI spec version: v1
 * Contact: api@webcrm.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;

namespace WebCrm.Rest.Model
{
    /// <summary>
    /// MoveDto
    /// </summary>
    [DataContract]
    public partial class MoveDto : BaseObject, IEquatable<MoveDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MoveDto" /> class.
        /// </summary>
        [JsonConstructor]
        protected MoveDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MoveDto" /> class.
        /// </summary>
        /// <param name="NewOrganisationId">NewOrganisationId (required).</param>
        public MoveDto(int? NewOrganisationId = default(int?))
        {
            // to ensure "NewOrganisationId" is required (not null)
            if (NewOrganisationId == null)
            {
                throw new InvalidDataException("NewOrganisationId is a required property for MoveDto and cannot be null");
            }
            else
            {
                this.NewOrganisationId = NewOrganisationId;
            }
        }
        
        /// <summary>
        /// Gets or Sets NewOrganisationId
        /// </summary>
        [DataMember(Name="NewOrganisationId", EmitDefaultValue=false)]
        public int? NewOrganisationId { get; set; }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MoveDto);
        }

        /// <summary>
        /// Returns true if MoveDto instances are equal
        /// </summary>
        /// <param name="input">Instance of MoveDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MoveDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.NewOrganisationId == input.NewOrganisationId ||
                    (this.NewOrganisationId != null &&
                    this.NewOrganisationId.Equals(input.NewOrganisationId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.NewOrganisationId != null)
                    hashCode = hashCode * 59 + this.NewOrganisationId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
